woowacourse-teams/2022-thankoo

backend/src/main/java/com/woowacourse/thankoo/common/config/WebConfig.java

feat: cors 설정

---

backend/src/main/java/com/woowacourse/thankoo/authentication/exception/InvalidAuthenticationException.java
backend/src/main/java/com/woowacourse/thankoo/authentication/exception/InvalidTokenException.java
backend/src/main/java/com/woowacourse/thankoo/authentication/infrastructure/JwtTokenProvider.java
backend/src/main/java/com/woowacourse/thankoo/authentication/presentation/AuthenticationContext.java
backend/src/main/java/com/woowacourse/thankoo/authentication/presentation/SignInInterceptor.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/BadRequestException.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/UnAuthorizedException.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/UnauthorizedException.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/dto/ErrorResponse.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponHistoryService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponType.java
backend/src/main/java/com/woowacourse/thankoo/coupon/exception/InvalidCouponTypeException.java
backend/src/main/java/com/woowacourse/thankoo/member/exception/InvalidMemberException.java

- ExceptionHandler를 사용하여 에러 핸들링
- 상세 에러타입 추가
Close #12

feat: ExceptionHandler 추가

---

frontend/src/App.tsx
frontend/src/commons/Main/GridViewCoupon.tsx
frontend/src/commons/SelectReceiver/CheckedUsers.tsx
frontend/src/commons/SelectReceiver/ListViewUser.tsx
frontend/src/commons/SelectReceiver/ListViewUsers.tsx
frontend/src/commons/SelectReceiver/UserSearchInput.tsx
frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts
frontend/src/hooks/SelectReceiver/useSelectReceiver.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/mainPageHandler.ts
frontend/src/mocks/selectReceiverPageHandlers.ts
frontend/src/pages/EnterCouponContent.tsx
frontend/src/pages/Main.tsx
frontend/src/pages/SelectReceiver.tsx

- 수신인 선택 페이지 UI 구현
- 전송할 쿠폰의 컨텐츠 작성 페이지 UI 구현
Close #17

feat: 쿠폰 전송 페이지 UI 구현

---

frontend/src/commons/Main/GridViewCoupon.tsx
frontend/src/mocks/dummyData.ts

feat: coupon 디자인 변경

---

backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/ContentRequest.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponRequest.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponContent.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponHistory.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponType.java
backend/src/main/java/com/woowacourse/thankoo/coupon/exception/InvalidCouponContentException.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponContentTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponHistoryQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponTypeTest.java

- coupon type, title, message의 제약 조건을 추가한다.
- CouponContent @Embeddable 클래스를 만들어 검증 로직을 분리한다.
Close #22

refactor: CouponContent 검증 로직 추가

---

backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponContent.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponHistoryAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/CouponFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/MemberFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/TestFixture.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponHistoryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponContentTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponHistoryQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponHistoryControllerTest.java

-  글자수가 빈칸 / 제한 넘는 경우
-  내용 글자수 제한 : 50 -> 100
-  로그인하지 않은 경우
Close #27

refactor: coupon 관련 Bad Case Test를 추가한다.

---

frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts

- 쿠폰 전송 페이지에서 선택된 모든 사람에게 쿠폰을 전송하도록 했다.
Close #46

refactor: 여러 사람에게 쿠폰 전송기능 구현

---

backend/src/main/java/com/woowacourse/thankoo/ThankooApplication.java
backend/src/main/java/com/woowacourse/thankoo/common/config/JpaConfig.java
backend/src/test/java/com/woowacourse/thankoo/common/ControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/common/annotations/RepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/member/domain/MemberRepositoryTest.java

- JpaConfig 분리
Close #43
이슈 내용 확인해주세요

refactor: JpaConfig 분리

---

backend/src/main/java/com/woowacourse/thankoo/member/domain/Member.java
backend/src/main/java/com/woowacourse/thankoo/member/domain/MemberRepository.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationStatus.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/TimeZoneType.java

- TimeZoneType 의 클래스명 이대로 괜찮을까요?
Close #58

feat: 예약 엔티티를 생성한다.

---

backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/thankoo/member/application/MemberService.java
backend/src/main/java/com/woowacourse/thankoo/member/domain/Member.java
backend/src/main/java/com/woowacourse/thankoo/member/presentation/MemberController.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/member/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/member/presentation/MemberControllerTest.java

feat: 내 정보 조회 기능

---

backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponStatus.java
backend/src/main/java/com/woowacourse/thankoo/coupon/exception/InvalidCouponException.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/dto/ReservationRequest.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationRepository.java
backend/src/main/java/com/woowacourse/thankoo/reservation/exception/InvalidReservationException.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/PresentationController.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/ReservationController.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/MemberFixture.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationTest.java

- 빠른 개발을 위해 서비스와 도메인 테스트만 진행했습니다.
- 네이밍 관련해서 피드백 주시면 좋을 것 같아요!
- 그리고 타임존 생성시 Asia를 디폴트로 받을지 고민되네요
- DTO에서 `@JsonFormat`을 사용해서 시간을 바인딩 했습니다~
- 프론트에서 넘어온 시간 값이 잘 못됐을 경우에 DTO에서 예외가 발생할텐데 이에 대한 처리는 테스트 코드 작성하면서 수정할게요.
- 아니면 String을 받아서 예약 도메인에서 파싱하는 방법도 고려해볼 수 있을것 같아요
Close #61

feat: 예약을 생성한다.

---

.github/workflows/backend.yml

- 구현한 기능을 적습니다.
- #75 
Close #75

chore: github workflow 수정

---

backend/build.gradle

chore: 빌드 시 docs가 jar 파일에 이동하도록 수정

---

frontend/src/pages/SignIn.tsx

- google redirect url 변경
- 프론트엔드 ci/cd 확인
Close #86

feat: google auth redirect url domain으로 수정

---

frontend/src/constants/api.ts

refactor: url 수정

---

backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponContentResponse.java

- CouponContentResponse 쿠폰 타입을 소문자로 변경
Close #93

refactor: CouponContentResponse 쿠폰 타입을 소문자로 변경한다.

---

frontend/src/App.tsx
frontend/src/components/RequestedCoupons/ListViewCoupon.tsx
frontend/src/constants/api.ts
frontend/src/constants/googleAuth.ts
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts
frontend/src/hooks/Main/useMain.ts
frontend/src/hooks/SelectReceiver/useSelectReceiver.ts
frontend/src/hooks/SignIn/useSignIn.ts
frontend/src/mocks/createReservationHandler.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/mainPageHandler.ts
frontend/src/mocks/sendCouponHandler.ts
frontend/src/mocks/signInHandler.ts
frontend/src/pages/SignIn.tsx
frontend/src/recoil/atom.ts

- 자동로그인 기능 구현
- 인증 기능 변경 (recoil 의존 제거)
- 인증 없이 dev server test 가능하게 하기
- auth를 없애면서 EnterCoupon Page에서 data fetching 하는 로직 살짝 변경함
- google Auth url 을 const 로 분리하였음(redirect url 등 확인하기 용이하게 하기 위해서)
- mock handler등이 local에서 최소한의 동작을 하도록 수정하였고, 빠진 handler(sendCoupon, signIn 등 추가)
Close #68

feat: 자동로그인 및 server State 의 recoil 의존 제거

---

frontend/src/constants/api.ts

hotfix: backend url 수정

---

backend/src/main/java/com/woowacourse/thankoo/common/config/WebConfig.java

refactor: cors origin 추가

---

backend/src/main/java/com/woowacourse/thankoo/common/config/WebConfig.java

refactor: origin을 모두 허용한다

---

frontend/src/components/@shared/BottomNavBar.tsx
frontend/src/components/@shared/Modal.tsx
frontend/src/components/Main/CouponDetails.tsx
frontend/src/components/Reservations/ListViewReservation.tsx
frontend/src/components/Reservations/Reservation.tsx
frontend/src/hooks/Reservations/useReservations.ts
frontend/src/pages/Main.tsx
frontend/src/pages/Reservations.tsx

- 모달창 dimmer 구현
- bottom nav  style 변경
Close #107

feat: design change

---

frontend/src/components/@shared/Header.tsx
frontend/src/components/Profile/SignOutButton.tsx
frontend/src/components/SelectReceiver/CheckedUsers.tsx
frontend/src/pages/UserProfile.tsx

- 로그아웃 버튼 클릭시 로컬스토리지 삭제 + navigate('sing-in')
Close #109

feat: 로그아웃 버튼 구현

---

frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts

- 보내는 사람 이름을 나오게 했다.
Close #111

feat: 쿠폰 보낼 때 보내는 사람 이름 보여주도록 수정

---

backend/src/docs/asciidoc/reservation.adoc
backend/src/test/java/com/woowacourse/thankoo/reservation/presentation/ReservationControllerTest.java

docs: 예약 관련 문서 추가

---

frontend/src/components/Reservations/ListViewReservation.tsx
frontend/src/components/Reservations/Reservation.tsx
frontend/src/constants/api.ts
frontend/src/hooks/Reservations/useReservations.ts
frontend/src/pages/Reservations.tsx

- 예약 페이지 예약 리스트 조회 api를 연동했다.
Close #114

feat: 예약 페이지 예약 리스트 조회 api를 연동한다.

---

frontend/src/components/@shared/PageLayout.tsx
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/Reservations/useReservations.ts
frontend/src/pages/CreateReservation.tsx

- 예약 요청 시 초까지 전송한다.
Close #116

refactor: 예약 요청 시 초까지 전송한다.

---

frontend/src/components/@shared/BottomNavBar.tsx
frontend/src/components/@shared/MyPageButton.tsx
frontend/src/components/@shared/PageLayout.tsx
frontend/src/components/@shared/ScheduledPageButton.tsx
frontend/src/components/@shared/SendButton.tsx
frontend/src/components/Main/CouponDetails.tsx
frontend/src/components/Reservations/ListViewReservation.tsx
frontend/src/components/Reservations/Reservation.tsx
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/Reservations/useReservations.ts
frontend/src/mocks/reservationsHandlers.js
frontend/src/mocks/reservationsHandlers.ts
frontend/src/pages/CreateReservation.tsx
frontend/src/pages/Reservations.tsx

- 요청받은 예약 리스트를 보내주는 api를 연동한다.
- bottom nav bar css를 수정한다.
Close #122

feat: 요청받은 예약 리스트를 보내주는 api를 연동한다.

---

frontend/src/components/Main/CouponDetails.tsx
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/mocks/dummyData.ts
frontend/src/mocks/reservationsHandlers.js
frontend/src/pages/CreateReservation.tsx
frontend/src/recoil/atom.ts
frontend/src/types/index.ts

fix: 쿠폰 예약 id 잘못가는 버그 수정

---

frontend/src/components/Reservations/Reservation.tsx

- 페이지 레이아웃 및 fetch 구현
- 승낙, 거절 기능 추가
Close #64

feature: 요청된 예약 페이지 완성

---

backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/dto/ReservationResponse.java

refactor: reservation 반환값 소문자로 변경

---

frontend/src/constants/coupon.ts
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/Main/useMain.ts
frontend/src/pages/Main.tsx

fix: 예약하기 버튼이 보이지 않던 문제 해결

---

frontend/src/App.tsx
frontend/src/constants/routes.ts
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts
frontend/src/hooks/useOnSuccess.ts
frontend/src/pages/Main.tsx
frontend/src/pages/OnSuccessPage.tsx

- 요청이 성공했을 시 체크모양 페이지로 사용자에게 알려줌
Close #132

feature: 요청 성공시 이동하는 페이지 구현

---

frontend/src/components/Reservations/Reservation.tsx
frontend/src/constants/coupon.ts
frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts
frontend/src/hooks/Main/useMain.ts
frontend/src/mocks/dummyData.ts
frontend/src/pages/Reservations.tsx
frontend/src/types/index.ts

- 쿠폰 status 타입이 맞지 않아 발생하던 오류를 제거한다.
- 예약 status 별로 선택할 수 있는 옵션을 다르게 한다.
Close #134

fix : 쿠폰 status 타입이 맞지 않아 발생하던 오류를 제거한다.

---

frontend/src/pages/Main.tsx

feat: 메인 페이지 헤더의 높이를 다른 페이지 헤더와 맞춘다.

---

frontend/src/App.tsx
frontend/src/constants/routes.ts
frontend/src/hooks/useOnFailure.ts
frontend/src/pages/OnFailurePage.tsx

- 실패시 보여줄 페이지 애니메이션 추가
- 실패 페이지 라우팅
- 실패 페이지 라우팅 후 timeout을 적용해서 원래 페이지로 이동할 수 있도록 hook 구현
Close #141

feature: failure page 추가

---

backend/src/main/java/com/woowacourse/thankoo/common/alert/SlackLoggerAspect.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationQueryService.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/dto/ReservationRequest.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationRepository.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/TimeZoneType.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/ReservationController.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/dto/ReservationResponse.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/presentation/ReservationControllerTest.java

- 코드 컨벤션 적용 (final, private 등등)
- 테스트 로직 코드리뷰 반영
- ReservationQueryService 에 @Transactional 추가
- 불필요한 코드 삭제
Close #143

refactor: 예약 조회 리팩토링

---

frontend/src/App.tsx
frontend/src/components/@shared/PageLayout.tsx
frontend/src/components/SelectReceiver/ListViewUsers.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/SelectReceiver.tsx

- 쿠폰 수신인 목록이 깨지던 것을 해결한다.
- 버튼이 레이아웃을 초과하던 문제를 해결한다.
Close #148

fix: 쿠폰 수신인 페이지 UI가 깨지던 문제를 해결한다.

---

frontend/src/components/SelectReceiver/CheckedUsers.tsx

feat: 선택된 유저 이름 정있게 다 보여주기

---

frontend/src/components/@shared/BottomNavBar.tsx
frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts
frontend/src/index.tsx
frontend/src/mocks/handlers.ts
frontend/src/mocks/profileHandlers.js
frontend/src/mocks/sendCouponHandler.ts
frontend/src/pages/EnterCouponContent.tsx

- 쿠폰 보내고 나서 선택된 수신인을 담는 전역 상태를 초기화한다.

feat: 쿠폰 보내면 수신인 선택한 전역 상태 초기화

---

backend/src/main/resources/logback-spring.xml

chore: dev 로깅 추가

---

frontend/src/index.tsx
frontend/webpack.config.js

- process.env.NODE_ENV를 console.log한다

chore:환경변수 설정을 테스트한다

---

frontend/src/index.tsx
frontend/webpack.config.js

- jenkins의 환경변수가 어느정도 해주는지 테스트한다.

chore: jenkins의 환경변수가 어느정도 해주는지 테스트한다.

---

backend/build.gradle

- 제곧내
- docs가 될 때도 있고 안될때도 있어서 오찌 블로그 방식으로 수정했어연 [링크](https://velog.io/@ohzzi/REST-Docs-%EC%96%B4%EB%94%9C-%EB%B3%B4%EC%8B%9C%EB%8A%94-%EA%B1%B0%EC%A3%A0-%EA%B7%B8%EA%B1%B4-%EC%A0%9C-%EC%9E%94%EC%83%81%EC%9E%85%EB%8B%88%EB%8B%A4%EB%A7%8C)

chore: 빌드 순서 수정

---

frontend/src/constants/googleAuth.ts

- google oauth redirect uri를 https로 변경한다.
Close #175

fix: google oauth redirect uri를 https로 변경한다.

---

backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepository.java

```java
private static RowMapper<MemberCoupon> rowMapper() {
return (rs, rowNum) ->
new MemberCoupon(rs.getLong("coupon_id"),
new Member(rs.getLong("sender_id"), rs.getString("sender_name"),
rs.getString("sender_email"), rs.getString("sender_social_id"),
rs.getString("sender_image_url")),
new Member(rs.getLong("receiver_id"), rs.getString("receiver_name"),
rs.getString("receiver_email"), rs.getString("receiver_social_id"),
rs.getString("receiver_image_url")),
rs.getString("coupon_type"),
rs.getString("title"),
rs.getString("message"),
rs.getString("status"));
}
```
sender와 receiver 분리, 수정 완료

refactor: 쿼리 수정

---

frontend/src/components/@shared/Input.tsx
frontend/src/components/@shared/TabsNav.tsx
frontend/src/pages/EnterNickname.tsx

- Input 커스텀 컴포넌트의 delete button을 span으로 바꾼다.
Close #178

fix: form의 버튼을 하나만 둬서 enter로 submit 가능하도록 수정한다.

---

frontend/src/components/@shared/Modal.tsx
frontend/src/components/Main/ConponDetails.notUsed.tsx
frontend/src/components/Main/CouponDetails.reserve.tsx
frontend/src/components/Main/CouponDetails.tsx
frontend/src/constants/api.ts
frontend/src/hooks/Main/useCouponDetail.ts
frontend/src/mocks/dummyData.ts
frontend/src/mocks/mainPageHandler.ts
frontend/src/types/index.ts

- 쿠폰 단건 조회에 대한 api를 연동하였다.
- 아직 디자인은 결정하지 못했다.
Close #181

feat: 단건 조회에 대한 api를 연동한다.

---

frontend/src/apis/axios.ts
frontend/src/components/Main/CouponDetails.reserve.tsx
frontend/src/components/Profile/SignOutButton.tsx
frontend/src/components/Reservations/Reservation.tsx
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts
frontend/src/hooks/EnterNickname/useEnterNickname.ts
frontend/src/hooks/Main/useCouponDetail.ts
frontend/src/hooks/Main/useMain.ts
frontend/src/hooks/Profile/useProfile.ts
frontend/src/hooks/Reservations/useReservations.ts
frontend/src/hooks/SelectReceiver/useSelectReceiver.ts
frontend/src/hooks/SignIn/useSignIn.ts
frontend/src/pages/UserProfile.tsx
frontend/src/utils/auth.ts

refactor : axios instance를 리팩토링한다.

---

frontend/src/components/@shared/HeaderText.tsx
frontend/src/hooks/Main/useMain.ts
frontend/src/pages/Main.tsx

- 보낸 쿠폰함 확인하는 api 연동
- 보낸 쿠폰함이라는 header를 클릭시 받은 쿠폰함과 보낸쿠폰함을 토글할 수 있다.
Close #180

feat: 보낸 쿠폰함 구현

---

frontend/src/apis/queryClient.ts
frontend/src/hooks/Main/useMain.ts

- 예약 중, 예약 완료, 사용 전 으로 우선순위 수정
- token 삭제 로직 clearAuth가 담당하도록 수정

refactor: 메인 페이지 쿠폰 순서를 조정한다.

---

frontend/src/components/@shared/Header.tsx
frontend/src/components/@shared/HeaderText.tsx
frontend/src/components/Main/ConponDetail.notUsed.tsx
frontend/src/components/Main/CouponDetail.reserve.tsx
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/GridViewCoupons.tsx
frontend/src/components/SelectReceiver/ListViewUsers.tsx
frontend/src/constants/coupon.ts
frontend/src/hooks/Main/useCouponDetail.ts
frontend/src/pages/Main.tsx

feat: 예약 중, 예약 완료 세부 정보 UI를 변경한다.

---

frontend/src/components/@shared/Header.tsx
frontend/src/components/Main/ConponDetail.notUsed.tsx
frontend/src/components/Main/CouponDetail.reserve.tsx
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/GridViewCoupons.tsx
frontend/src/hooks/Main/useCouponDetail.ts
frontend/src/index.tsx
frontend/src/pages/Reservations.tsx
frontend/src/styles/GlobalStyled.tsx

- 첫번째 페이지는 쿠폰 디테일
- 두번째 페이지는 예약 디테일
- 드래그로 페이지 전환 가능
- 버튼을 통한 페이지 전환 가능
- 버튼 active상태가 드래그로 보여지는 화면에 따라서 동기화 되도록 변경
- 전체적 모달창 디자인 변경
- forward ref를 통해서 page관리
- 현재 보여지는 page state는 scroll x 위치로 관리
- 버튼 클릭시 scroll into를 이용해서 해당 ref로 이동
- 세부사항은코드에 직접 첨부하겠음
Close #202

feat: 쿠폰 디테일 페이지를 수정한다

---

backend/src/docs/asciidoc/coupon.adoc
backend/src/docs/asciidoc/meeting.adoc
backend/src/docs/asciidoc/reservation.adoc
backend/src/main/java/com/woowacourse/thankoo/common/dto/TimeResponse.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponContentResponse.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponResponse.java
backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/dto/MeetingResponse.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/dto/ReservationResponse.java

- 제곧내
- 더불어 문서화 까지~
Close: #199

refactor: 반환 값에 소문자, 날짜 포맷을 수정한다.

---

frontend/src/hooks/Main/useCouponDetail.ts

- 화면 사이즈에 맞게 동기화 되도록
- 버튼 작동 안되던 버그 수정

Fix: Coupon detail 버튼과 slide가 동기화가 잘 안되는 버그 수정

---

backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/dto/SimpleMeetingResponse.java
backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logback/file-debug-logger.xml
backend/src/main/resources/logback/file-error-logger.xml
backend/src/main/resources/logback/file-info-logger.xml
backend/src/main/resources/logback/file-sql-slow-info-logger.xml
backend/src/main/resources/logback/file-warn-logger.xml

refactor: 로깅 전략 수정

---

backend/src/main/java/com/woowacourse/thankoo/common/validator/MeetingTimeRequestValidator.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/ReservationAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/ReservationAssured.java

refactor: MeetingTime에 연도 차이가 있을 경우 예외가 발생한다

---

frontend/package.json
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/GridViewCoupons.tsx
frontend/src/components/Reservations/Reservation.tsx
frontend/src/constants/coupon.ts
frontend/src/hooks/Main/domain/useCouponDetail.ts
frontend/src/hooks/Reservations/queries/reservations.ts
frontend/src/pages/EnterNickname.tsx
frontend/src/pages/Meetings.tsx
frontend/src/pages/UserProfile.tsx

feat: 쿠폰 상태, 쿠폰함의 상태에 따라 쿠폰 디테일의 버튼 변경 및 상호작용 변경

---

frontend/src/App.tsx
frontend/src/components/@shared/Toast.tsx
frontend/src/hooks/Profile/useProfile.ts
frontend/src/hooks/useToast.ts
frontend/src/recoil/atom.ts
frontend/src/routes/Router.tsx

feature: toast ui

---

backend/src/main/java/com/woowacourse/thankoo/meeting/application/MeetingQueryService.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/dto/MeetingQueryCondition.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingQueryRepository.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingQueryRepositoryTest.java

refactor: 미팅이 현재 시간 이후이면서 진행중일 경우에만 조회하도록 변경

---

backend/src/main/java/com/woowacourse/thankoo/common/domain/TimeUnit.java
backend/src/main/java/com/woowacourse/thankoo/common/dto/TimeResponse.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meeting.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingCoupon.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingRepository.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/ReservationMeetingService.java
backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/dto/MeetingResponse.java
backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/dto/SimpleMeetingResponse.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/dto/ReservationResponse.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/ReservationFixture.java
backend/src/test/java/com/woowacourse/thankoo/coupon/infrastructure/CouponClientTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingMemberTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/TimeUnitTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationTest.java

refactor: 예약과 미팅 생성시 시간을 검증한다.

---

frontend/src/components/@shared/ChoiceSlider.tsx
frontend/src/components/@shared/Time.tsx
frontend/src/components/@shared/Toast.tsx
frontend/src/components/Profile/ProfileUserImage.tsx
frontend/src/components/Profile/SignOutButton.tsx
frontend/src/components/Reservations/ListViewReservation.tsx
frontend/src/components/Reservations/Reservation.tsx
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/Main/domain/useCouponDetail.ts
frontend/src/hooks/Main/queries/couponDetail.ts
frontend/src/hooks/Profile/useProfile.ts
frontend/src/hooks/Reservations/queries/reservations.ts
frontend/src/hooks/useToast.ts
frontend/src/pages/CreateReservation.tsx
frontend/src/pages/Meetings.tsx
frontend/src/pages/UserProfile.tsx
frontend/src/recoil/atom.ts

- [이슈 참조](https://github.com/woowacourse-teams/2022-thankoo/issues/233)
Close #233

fix: 버그 픽스

---

frontend/src/hooks/Meetings/domain/useMeetings.ts
frontend/src/pages/Meetings.tsx
frontend/src/pages/UserProfile.tsx
frontend/src/styles/GlobalReset.tsx

fix: 사파리 버그 수정

---

frontend/src/hooks/Meetings/domain/useMeetings.ts
frontend/src/pages/Meetings.tsx

- meeting list 오류 해결
Close #이슈번호

fix: meeting list 오류

---

frontend/src/hooks/Meetings/domain/useMeetings.ts

- 미팅 약속 날짜 계산 로직 수정
Close #이슈번호

fix: 날짜 계산 로직 수정

---

backend/build.gradle
backend/src/main/java/com/woowacourse/thankoo/authentication/application/dto/SignUpRequest.java
backend/src/main/java/com/woowacourse/thankoo/authentication/presentation/SignInInterceptor.java
backend/src/main/java/com/woowacourse/thankoo/authentication/presentation/dto/TokenResponse.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/common/logging/LoggingAspect.java
backend/src/main/java/com/woowacourse/thankoo/common/logging/MaskingUtil.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/ContentRequest.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponRequest.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponContentResponse.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponDetailResponse.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponResponse.java
backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/dto/SimpleMeetingResponse.java
backend/src/main/java/com/woowacourse/thankoo/member/application/dto/MemberNameRequest.java
backend/src/main/java/com/woowacourse/thankoo/member/presentation/dto/MemberResponse.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/dto/ReservationRequest.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/dto/ReservationStatusRequest.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/dto/SimpleReservationResponse.java
backend/src/main/resources/logback-access.xml
backend/src/main/resources/logback/console-access-logger.xml
backend/src/main/resources/logback/file-access-logger.xml

- 이슈에 상세 내용 적어두었습니다.
- 최신 버전은 작동을 안합니다. 버전 변경하면 안돼요!!
`implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'`
- Response도 로그로 남겨야할까요?
- file-access-logger 사이즈
Close #238

refactor: 로깅 전략을 수정한다.

---

backend/src/docs/asciidoc/coupon.adoc
backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponQueryService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponTotal.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponTotalResponse.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponAssured.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java

feat: 주고, 받은 쿠폰 개수 api 구현

---

frontend/src/components/PageButton/CouponListPageButton.tsx
frontend/src/components/PageButton/ReservationPageButton.tsx
frontend/src/components/PageButton/ScheduledPageButton.tsx

- 선택된 nav만 색을 주고 나머지는 어둡게 표현
- nav에 헷갈리지 않게 글씨추가

feat: 바텀 nav 디자인 변경

---

frontend/src/constants/googleAuth.ts

fix: dev와 prod의 clientID 분리

---

frontend/src/components/@shared/Input.tsx
frontend/src/constants/coupon.ts
frontend/src/constants/users.ts
frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts
frontend/src/hooks/Profile/useProfile.ts
frontend/src/pages/EnterCouponContent.tsx
frontend/src/pages/EnterNickname.tsx
frontend/src/pages/UserProfile.tsx

- 닉네임 입력 글자수 제한
- 쿠폰 제목 글자수 제한
- 쿠폰 내용 글자수 제한
-  마이페이지 글자수 제한
Close #266

feat: 글자수 제한

---

.github/workflows/sonarqube.yml
backend/build.gradle

- 정적 분석을 위한 sonarqube 와 Jacoco 적용
- Github Actions 로 develop 브랜치에 pull request, push 될 때 마다 정적분석 리포트를 생성하도록 구현
Close #259

chore: Sonarqube 와 Jacoco 적용

---

backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java

fix: test 에러 수정

---

.github/workflows/backend.yml
backend/src/test/java/com/woowacourse/thankoo/member/domain/MemberRepositoryTest.java

- 라벨기준이 아닌 변경 지점을 `backend/**`로 지정
- 새로 열리거나, 새로 push가 날라오면 작동
Close #276

chore: 깃헙 액션 flow를 수정한다

---

backend/src/main/java/com/woowacourse/thankoo/alarm/support/MessageFormatter.java
backend/src/test/java/com/woowacourse/thankoo/alarm/support/MessageFormatterTest.java

- 이슈 참고
- depth가 조금 혐인데, 알고리즘과 같은 코드라 어쩔 수가 없네요 ㅠ
- 이 클래스 사용을 통해 편리성이 높아진다면, 사용 고려해보아요
```java
MessageFormatter.format("보내는 이 : {}, 쿠폰 종류 : {}, 메시지 : {}", "후니", "커피", "사랑해요");
// "보내는 이 : 후니, 쿠폰 종류 : 커피, 메시지 : 사랑해요"
```
Close #282

feat: 알람용 messageFormatter 생성

---

backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
backend/src/main/java/com/woowacourse/thankoo/alarm/support/MessageFormatter.java
backend/src/main/java/com/woowacourse/thankoo/authentication/exception/GoogleClientException.java
backend/src/main/java/com/woowacourse/thankoo/authentication/infrastructure/GoogleClient.java
backend/src/main/java/com/woowacourse/thankoo/common/logging/MaskingUtil.java
backend/src/main/java/com/woowacourse/thankoo/common/validator/MeetingTimeRequestValidator.java
backend/src/main/java/com/woowacourse/thankoo/coupon/infrastructure/integrate/dto/MeetingResponse.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingMembers.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingRepository.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meetings.java
backend/src/main/java/com/woowacourse/thankoo/member/domain/Email.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationQueryService.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/dto/ReservationRequest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/MeetingAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/authentication/infrastructure/AuthorizationExtractorTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/member/presentation/MemberControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java

- sonarqube 리포트를 보고 리팩터링 한다.
Close #284

refactor: sonarqube 코드 스멜을 리팩터링한다.

---

.github/workflows/frontend.yml

chore: 프론트엔드 테스트용 workflow 생성

---

frontend/src/components/CreateReservation/ConfirmReservationModal.tsx
frontend/src/components/EnterCouponContent/ConfirmCouponContentModal.tsx
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/pages/CreateReservation.tsx
frontend/src/pages/EnterCouponContent.tsx
frontend/src/pages/Main.tsx

- 모달 중앙에서 안뜨는 에러 수정
- 예약 수신인 반대로 나오던 에러 수정
- 쿠폰 모달에서 쿠폰 타입 보여주도록 추가
Close #320 #319

fix: QA 중 나온 오류를 해결한다.

---

frontend/src/components/@shared/Time.tsx
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/GridViewCoupons.tsx
frontend/src/constants/api.ts
frontend/src/hooks/Main/domain/useCouponDetail.ts
frontend/src/hooks/Main/domain/useMain.ts
frontend/src/hooks/Main/queries/coupons.ts
frontend/src/hooks/Profile/useProfile.ts
frontend/src/pages/Main.tsx
frontend/src/utils/index.ts

- 사용완료한 쿠폰도 볼 수 있도록 하는 버튼을 추가했습니다.
- 유저 이름을 변경하는 api가 변경돼서 수정했습니다.
- map 중에서 key가 없는 애들 달아줬습니다.
Close #313

feat: 모든 쿠폰 이력 보기 버튼 추가

---

backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponQueryService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponStatus.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/MeetingProvider.java
backend/src/main/java/com/woowacourse/thankoo/coupon/infrastructure/integrate/JpaMeetingProvider.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingRepository.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponStatusTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/infrastructure/integrate/JpaMeetingProviderTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java

refactor: 사용한 쿠폰에 대해서도 미팅 정보를 조회한다

---

backend/src/main/java/com/woowacourse/thankoo/common/util/FileProfileImageGenerator.java
backend/src/test/java/com/woowacourse/thankoo/authentication/util/ProfileImageGeneratorTest.java
backend/src/test/java/com/woowacourse/thankoo/common/util/ProfileImageGeneratorTest.java

fix: jar파일 실행 시 파일 못읽어오는 문제 해결

---

backend/src/main/java/com/woowacourse/thankoo/common/exception/dto/ErrorResponse.java
backend/src/main/java/com/woowacourse/thankoo/common/logging/LoggingAspect.java

refactor: 에러 응답 body를 info 로그를 남긴다

---

backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponContent.java
backend/src/main/java/com/woowacourse/thankoo/member/domain/Name.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponContentTest.java
backend/src/test/java/com/woowacourse/thankoo/member/domain/NameTest.java

- 이름, 쿠폰 내용 앞/뒤 공백 제거
Close #330

refactor: 이름, 쿠폰 내용 앞/뒤 공백 제거

---

.github/workflows/backend.yml
.github/workflows/sonarqube.yml
backend/build.gradle

refactor: 소나큐브 설정 수정

---

frontend/src/components/@shared/noContent/NoReceivedCoupon.tsx
frontend/src/constants/api.ts
frontend/src/constants/routes.ts
frontend/src/hooks/@queries/hearts.ts
frontend/src/hooks/@queries/members.ts
frontend/src/pages/Hearts.tsx
frontend/src/routes/Router.tsx

- 마음 보내기 가능
- 마음은 받아야만 보낼 수 있음, 혹은 처음인 경우에만

feat: 마음 보내기 기능을 구현한다.

---

backend/src/main/java/com/woowacourse/thankoo/heart/application/HeartService.java
backend/src/main/java/com/woowacourse/thankoo/heart/application/dto/HeartMessage.java

refactor: 마음 보내기 알림 추가

---

backend/src/main/java/com/woowacourse/thankoo/heart/application/dto/HeartMessage.java

fix: emptylist 반환

---

frontend/src/pages/Hearts.tsx

- 마음 페이지의 UI width가 100vw로 돼있어 깨지던 문제를 해결한다.
- 보낼 수 없어도 api call이 가던 오류를 해결한다.

fix: 마음 페이지 웹에서 UI가 깨지는 문제 해결

---

frontend/src/components/Main/GridViewCoupons.tsx
frontend/src/hooks/Reservations/queries/reservations.ts
frontend/src/pages/Hearts.tsx

- 마음 페이지에 검색 기능을 추가했다.
- 사용완료 폰트 사이즈를 키웠다.
- 토스트 메세지를 하나만 나오도록 했다.

fix: 마음 페이지 검색 기능 추가

---

frontend/src/apis/queryClient.ts

fix: auth 관련 오류를 수정한다.

---

frontend/src/apis/queryClient.ts

fix:error response에 optional 추가

---

backend/script/deploy.sh

- 배포 스크립트를 작성하여 jenkins가 이 파일을 던지도록 수정합니다.
Close #365

chore: 배포 스크립트를 작성한다

---

backend/script/deploy.sh

- 기존 내용을 복사 붙여넣기 했는데, 쌍따옴표가 이상한 형태로 들어가서 수정했습니다.

refactor: 스크립트 설명을 수정한다

---

backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java
backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackClient.java
backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/dto/SlackUserResponse.java
backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/dto/SlackUsersResponse.java
backend/src/main/resources/application-test.yml

refactor: 알림 관련 로직을 리팩토링한다.

---

backend/src/main/java/com/woowacourse/thankoo/common/logging/LoggingAspect.java
backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
backend/src/main/java/com/woowacourse/thankoo/common/schedule/ReservationScheduleTask.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponTotalResponse.java
backend/src/main/java/com/woowacourse/thankoo/heart/presentation/dto/ReceivedHeartResponse.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/MeetingService.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingRepository.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationRepository.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservations.java
backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationsTest.java

- 10시 ~ 20시 사이에 30분 간격으로 수락되지 않은 예약을 취소한다.
- 미팅도 10시 ~ 20시 사이에 30분 간격으로 완료시키도록 한다.
Close #341

feat: 10시 ~ 19시 30분 사이에 30분 간격으로 수락되지 않은 예약을 취소하는 기능

---

frontend/package.json

feature: dev-build 추가

---

frontend/package.json

feat: dev-build 수정

---

frontend/src/constants/googleAuth.ts
frontend/src/index.tsx
frontend/webpack/webpack.dev.js

fix: webpack 수정

---

frontend/src/constants/googleAuth.ts
frontend/src/index.tsx
frontend/webpack/webpack.dev.js

fix: webpack 설정 확인

---

frontend/src/components/PageButton/CouponListPageButton.tsx
frontend/src/components/Profile/ProfileUserImage.tsx
frontend/src/components/Profile/SelectProfileImgModal.tsx
frontend/src/hooks/@queries/profile.ts
frontend/src/hooks/Profile/useUserProfile.ts
frontend/src/pages/UserProfile.tsx

```
PUT /api/members/me/profile-image HTTP/1.1
Content-Type: application/json;charset=UTF-8
Authorization: Bearer accessToken
Accept: application/json
Content-Length: 44
Host: localhost:8080
{"imageUrl":"/profile-image/user_skull.svg"}
```
Close #397

refactor: 유저 이미지 변경 요청 api가 변경된 것에 따른 프론트엔드 코드 수정

---

backend/src/main/resources/logback/file-access-logger.xml
backend/src/main/resources/logback/file-info-logger.xml

refactor: infor, access level logback 설정 변경

---

backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/MemberCoupon.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponResponse.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java

refactor: 쿠폰 API 응답에 쿠폰 생성 날짜 추가

---

frontend/src/components/PageButton/ReservationPageButton.tsx
frontend/src/hooks/@queries/reservation.ts

- ReservationButton에서 받은 예약을 불러오고 보여준다.
Close #404

feat: 요청받은 예약을 bottom nav에서 보여주는 기능 구현

---

backend/build.gradle
backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java
backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/slack/SlackClient.java
backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/slack/SlackUsersClient.java
backend/src/main/java/com/woowacourse/thankoo/authentication/infrastructure/GoogleClient.java
backend/src/main/java/com/woowacourse/thankoo/common/alert/MessageGenerator.java
backend/src/main/java/com/woowacourse/thankoo/common/alert/SlackAlarmFailedEvent.java
backend/src/main/java/com/woowacourse/thankoo/common/alert/SlackAlarmFailedListener.java
backend/src/main/java/com/woowacourse/thankoo/common/alert/SlackLoggerAspect.java
backend/src/main/java/com/woowacourse/thankoo/common/config/WebConfig.java
backend/src/test/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSenderTest.java

- 이슈에 RestTemplate 빈 등록에 대해 상세히 적어두었습니다.
- 알람 에러는 보면 쉽게 이해할 수 있을 거에요.
Close #408

refactor: 알람 에러시 알람 내용에 대한 로그를 남긴다.

---

frontend/public/index.html
frontend/src/styles/GlobalStyled.tsx

- 폰트를 다이나믹 서브셋으로 변경했다.
Close #412

refactor: 폰트 다이나믹 서브셋으로 변경

---

backend/src/main/java/com/woowacourse/thankoo/admin/coupon/domain/AdminCouponRepository.java
backend/src/main/java/com/woowacourse/thankoo/admin/meeting/domain/AdminMeetingRepository.java
backend/src/main/java/com/woowacourse/thankoo/admin/reservation/domain/AdminReservationRepository.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/dto/MeetingMessage.java
backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java

refactor: 미팅 알람 메시지 리팩터링

---

frontend/webpack/webpack.prod.js

feat: 프로덕션환경에서 웹팩 해시설정 추가

---

frontend/src/components/@shared/ProfileIcon.tsx
frontend/src/components/@shared/noContent/NoMeeting.tsx
frontend/src/components/@shared/noContent/NoReceivedCoupon.tsx
frontend/src/components/@shared/noContent/NoReservation copy.tsx
frontend/src/components/@shared/noContent/NoSendCoupon.tsx
frontend/src/components/@shared/toast/ToastItem.tsx
frontend/src/components/Main/ConponDetail.coupon.tsx
frontend/src/constants/coupon.ts
frontend/src/mocks/dummyData.ts
frontend/src/pages/Hearts.tsx
frontend/src/pages/SignIn.tsx
frontend/src/styles/mixIn.ts
frontend/src/types/date.d.ts
frontend/src/types/index.ts

- 쿠폰 디테일 모달에서 보낸 날짜를 보여준다.
Close #418

feat: 쿠폰 디테일 모달에서 보낸 날짜를 보여준다.

---

frontend/src/routes/Router.tsx

- header/ nav pr에서 잘못 수정한 버그를 fix 합니다

fix: 잘못된 route 수정

---

backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationQueryRepository.java

- 날짜 기준이 아닌 시간 순으로 정렬한다.
Close #439

refactor: 대기중인 예약 목록 조회 쿼리 수정

---

frontend/src/components/@shared/Modal.tsx
frontend/src/components/@shared/Modal/BottomSheetLayout.tsx
frontend/src/components/CreateReservation/ConfirmReservationModal.tsx
frontend/src/components/EnterCouponContent/ConfirmCouponContentModal.tsx
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/QRCouponRegisterModal.tsx
frontend/src/constants/api.ts
frontend/src/hooks/useQRCoupon.tsx
frontend/src/pages/EnterCouponContent.tsx
frontend/src/pages/Main.tsx
frontend/src/recoil/atom.ts
frontend/src/routes/Router.tsx
frontend/src/styles/Animation.ts

- QR을 통해 페이지에 접근하면 쿠폰을 등록시키는 모달을 띄운다.
Close #442

feat: QR을 통해 페이지에 접근하면 쿠폰을 등록시키는 모달을 띄운다.

---

backend/script/deploy.sh

- 스크립트에서 리눅스 로그 남기는 것을 제거합니다. (용량, 성능에 약간씩 이슈. 그리고 이미 로그백을 이용한 로깅 존재)

refactor: linux 로그 제거

---

backend/src/main/resources/application-test.yml

refactor: tomcat, hikari pool 설정

---

backend/script/deploy.sh

refactor: script 지속되는 버그 수정

---

backend/script/deploy.sh

fix: script 오타수정

---

backend/src/main/java/com/woowacourse/thankoo/serial/presentation/dto/CouponSerialResponse.java
backend/src/test/java/com/woowacourse/thankoo/serial/application/CouponSerialQueryServiceTest.java

fix: 쿠폰 시리얼의 쿠폰 타입을 소문자로 응답한다.

---

backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponTest.java

- 자기 자신에게 쿠폰을 보내는 버그 해결
Close #452

refactor: coupon을 본인에게 보내는 이슈 해결

---

backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/MeetingService.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meetings.java
backend/src/main/java/com/woowacourse/thankoo/member/domain/Members.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingsTest.java

refactor: 오늘의 미팅 알람시 미팅이 당일에 여러개여도 한 번만 보내도록 수정

---

frontend/src/components/@shared/Modal.tsx
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/QRCouponRegisterModal.tsx
frontend/src/components/Reservations/Reservation.tsx
frontend/src/hooks/@queries/meeting.ts
frontend/src/hooks/@queries/reservation.ts
frontend/src/hooks/Main/useCouponDetail.ts
frontend/src/pages/Main.tsx
frontend/src/types/index.ts

- QR을 통한 쿠폰 등록의 성공과 실패 시 각각 메시지를 띄운다.
- 예약 요청에 대한 응답이 올바르게 표시되도록 수정한다.
Close #454

fix: QR 쿠폰 등록과 예약 요청 응답에 대한 성공 실패를 대응한다.

---

backend/src/main/java/com/woowacourse/thankoo/admin/serial/domain/AdminSerialCodes.java
backend/src/test/java/com/woowacourse/thankoo/serial/domain/CouponSerialContentTest.java
backend/src/test/java/com/woowacourse/thankoo/serial/domain/CouponSerialTest.java

- final static -> static final
- delete public keyword in test code
Close #이슈번호

style: 시리얼 관련 코드를 컨벤션에 맞게 수정한다.

---

frontend/src/hooks/useQRCoupon.tsx
frontend/src/routes/Router.tsx

- 이슈와 동일
- 추후에 code 외의 로직에서도 사용가능하게 modify
Close #451

feat: 로그인 후 다시 code로 요청 보내는 기능추가

---

frontend/src/components/Reservations/Reservation.tsx
frontend/src/hooks/@queries/reservation.ts
frontend/src/hooks/Main/useCouponDetail.ts

-  예약 페이지에서 예약 요청 응답에 대한 성공 실패 여부 토스트를 띄운다.
Close #467

feat: 예약 페이지에서 예약 요청 응답에 대한 성공 실패 여부 토스트를 띄운다.

---

frontend/src/hooks/useQRCoupon.tsx
frontend/src/pages/Main.tsx

- localStorage를 무조건 비움으로써 문제 해결.
Close #469

fix: 모달 두번 뜨는 문제를 해결한다.

---

frontend/src/components/Main/QRCouponRegisterModal.tsx
frontend/src/hooks/useQRCoupon.tsx

v1.1.2 배포 (#478)

---

backend/build.gradle

- prometheus로 jvm을 모니터링할 수 있도록 세팅하였습니다.
Close #488

chore: 모니터링 추가

---

backend/src/main/java/com/woowacourse/thankoo/serial/application/CouponSerialService.java
backend/src/test/java/com/woowacourse/thankoo/serial/application/CouponSerialServiceTest.java

- 커피 타입만 반환되는 문제를 수정했습니다 
Close #494

fix: 시리얼로 쿠폰을 만들때 타입이 적용되도록 수정

---

backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/CodeGenerator.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/Organization.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationCode.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationMember.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationMembers.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationName.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationRepository.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationValidator.java
backend/src/main/java/com/woowacourse/thankoo/organization/exception/InvalidOrganizationException.java
backend/src/main/java/com/woowacourse/thankoo/organization/infrastructure/OrganizationCodeGenerator.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/AlarmFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/CouponFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/MemberFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/OAuthFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/OrganizationFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/ReservationFixture.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/SerialFixture.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationCodeTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationMemberTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationNameTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationValidatorTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/infrastructure/FakeCodeGenerator.java
backend/src/test/java/com/woowacourse/thankoo/organization/infrastructure/OrganizationCodeGeneratorTest.java

feat: Organization 엔티티를 생성한다.

---

backend/script/deploy-nonstop.sh
backend/script/nginx-conf.sh

- 이슈에 적어두었습니다.
- 무중단 배포를 학습하고 빠르게 적용하기 위해 Blue Green 기준으로 스크립트를 작성해두었습니다. 무중단 배포에 대해 학습하고 직접 스크립트도 실행시켜보면서 자연스럽게 익혀보면 좋을 것 같아요.
Close #504

chore: 무중단 배포 스크립트를 작성한다.

---

backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponQueryService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/ContentCommand.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponCommand.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponRequest.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponSelectCommand.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/MemberCoupon.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerialMember.java
backend/src/main/resources/application-test.yml
backend/src/test/java/com/woowacourse/thankoo/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/HeartAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/OrganizationAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponAssured.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/OrganizationFixture.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/serial/domain/CouponSerialMemberTest.java

- 라라의 기능이 추가되면 save, useImmediately에 대해서는 수정할 예정이에요
- @Deprecated가 살아있는 애들은 아직 다른 인수테스트에서 사용 중인 내용이에요 이후 인수테스트가 다 수정되면 Deprecated 내용을 지울게요. (센스있게 각 도메인 인수테스트에서 새 controller로 변경해주면 감사 ㅎ)
Close #524

refactor: coupon에 organization을 넣는다.

---

backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponQueryService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/MeetingQueryService.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/dto/MeetingQueryCondition.java
backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/MeetingController.java
backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationQueryService.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/ReservationController.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/MeetingAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/ReservationAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/MeetingAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/ReservationAssured.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/presentation/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/presentation/ReservationControllerTest.java

refactor: 예약과 미팅 조회에서 organization을 추가한다.

---

backend/src/docs/asciidoc/admin.adoc
backend/src/main/java/com/woowacourse/thankoo/admin/organization/application/AdminOrganizationService.java
backend/src/main/java/com/woowacourse/thankoo/admin/organization/application/dto/AdminOrganizationCreationRequeest.java
backend/src/main/java/com/woowacourse/thankoo/admin/organization/application/dto/AdminOrganizationCreationRequest.java
backend/src/main/java/com/woowacourse/thankoo/admin/organization/domain/AdminOrganizationRepository.java
backend/src/main/java/com/woowacourse/thankoo/admin/organization/presentaion/AdminOrganizationController.java
backend/src/test/java/com/woowacourse/thankoo/admin/common/AdminControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/admin/organization/application/AdminOrganizationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/admin/organization/presentaion/AdminOrganizationControllerTest.java

- 어드민에서 조직을 생성해주는 기능 구현
Close #521

feat: 어드민에서 조직을 생성하는 API를 구현한다.

---

backend/src/docs/asciidoc/organization.adoc
backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
backend/src/main/java/com/woowacourse/thankoo/heart/domain/Heart.java
backend/src/main/java/com/woowacourse/thankoo/organization/application/OrganizationService.java
backend/src/main/java/com/woowacourse/thankoo/organization/application/dto/OrganizationJoinRequest.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/Organization.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationCode.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationMember.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationMembers.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationRepository.java
backend/src/main/java/com/woowacourse/thankoo/organization/presentation/OrganizationController.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/OrganizationAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/OrganizationAssured.java
backend/src/test/java/com/woowacourse/thankoo/common/fixtures/OrganizationFixture.java
backend/src/test/java/com/woowacourse/thankoo/organization/application/OrganizationQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/application/OrganizationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationMemberTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationMembersTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/presentation/OrganizationControllerTest.java

- 조직 변경시 최근 접근 조직을 변경한다.
**PUT** `/organizations/{orgainzationId}/access`
- requestBody 없음
- responseBody 없음
- last-accessed 를 기준으로 잡다보니 접근한다라는 표현들로 통일했는데 `조직에 접근한다`는 표현 어떤가요? 괜찮은듯 아닌듯 고민되네요 ㅎ
Close #543

feat: 조직 변경시 최근 접근 조직을 변경한다.

---

backend/src/test/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/admin/serial/domain/AdminCouponSerialQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/serial/domain/CouponSerialQueryRepositoryTest.java

local 에서는 성공하는 테스트케이스가 Jenkins 서버에서 빌드시 실패하여 @Disabled 처리 했습니다.
Close #549

test: Jenkins 에서 실패하는 테스트케이스를 @Disabled 처리한다.

---

backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/AdminControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/dto/AdminErrorResponse.java

- 어드민 API에서 발생하는 예외를 핸들링하는 Controller Advice 구현
Close #547

feat: 어드민 API 예외를 핸들링한다.

---

backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/AdminControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java

- 각 ControllerAdive가 담당할 패키지를 추가해 어드민 에러 핸들링.
Close #552

feat: 각 ControllerAdvice가 처리할 basePackage 를 추가한다.

---

backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/MeetingController.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/ReservationController.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/MeetingAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/ReservationAssured.java
backend/src/test/java/com/woowacourse/thankoo/meeting/presentation/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/presentation/ReservationControllerTest.java

- 해당 PR은 refactor/organization-url-coupon 브랜치에 먼저 머지되어야 합니다. 
Close #557

refactor: 예약, 미팅 관련 기능에 API 명세를 수정한다.

---

backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/ContentRequest.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponRequest.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponUseCommand.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponUssCommand.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponUseRequest.java
backend/src/main/java/com/woowacourse/thankoo/meeting/presentation/MeetingController.java
backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/ReservationController.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/MeetingAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/ReservationAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/MeetingAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/MemberAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/ReservationAssured.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/meeting/presentation/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/reservation/presentation/ReservationControllerTest.java

refactor: 쿠폰 관련 기능에 조직 api 명세를 수정한다.

---

backend/src/docs/asciidoc/organization.adoc
backend/src/main/java/com/woowacourse/thankoo/organization/application/OrganizationQueryService.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/SimpleOrganization.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/SimpleOrganizationData.java
backend/src/main/java/com/woowacourse/thankoo/organization/presentation/OrganizationController.java
backend/src/main/java/com/woowacourse/thankoo/organization/presentation/dto/SimpleOrganizationResponse.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/OrganizationAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/OrganizationAssured.java
backend/src/test/java/com/woowacourse/thankoo/organization/application/OrganizationQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/presentation/OrganizationControllerTest.java

feat: 코드로 조직을 조회한다.

---

backend/src/main/java/com/woowacourse/thankoo/alarm/application/dto/Message.java
backend/src/main/java/com/woowacourse/thankoo/heart/application/HeartService.java
backend/src/main/java/com/woowacourse/thankoo/heart/application/dto/HeartSendCommand.java
backend/src/main/java/com/woowacourse/thankoo/heart/application/dto/HeartSendRequest.java
backend/src/main/java/com/woowacourse/thankoo/heart/presentation/HeartController.java
backend/src/main/java/com/woowacourse/thankoo/heart/presentation/dto/HeartRequest.java
backend/src/main/java/com/woowacourse/thankoo/serial/presentation/CouponSerialController.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponSerialAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/HeartAssured.java
backend/src/test/java/com/woowacourse/thankoo/alarm/application/dto/MessageTest.java
backend/src/test/java/com/woowacourse/thankoo/heart/application/HeartServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/heart/presentation/HeartControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/serial/presentation/CouponSerialControllerTest.java

refactor: 마음, 쿠폰 시리얼 관련 기능에 조직 api 명세를 수정한다. 

---

backend/src/main/java/com/woowacourse/thankoo/admin/organization/application/AdminOrganizationService.java
backend/src/main/java/com/woowacourse/thankoo/admin/organization/application/dto/AdminGetOrganizationsRequest.java
backend/src/main/java/com/woowacourse/thankoo/admin/organization/domain/AdminOrganizationRepository.java
backend/src/test/java/com/woowacourse/thankoo/admin/organization/application/AdminOrganizationServiceTest.java

- 조직을 검색하는 API에서 검색 기준인 날짜를 request url query에서 인식하지 못하는 문제 해결
Close #576

fix: 요청 url query를 인식하지 못하는 문제를 해결한다

---

backend/src/docs/asciidoc/member.adoc
backend/src/docs/asciidoc/organization.adoc
backend/src/main/java/com/woowacourse/thankoo/alarm/application/AlarmEventListener.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/thankoo/member/application/MemberQueryService.java
backend/src/main/java/com/woowacourse/thankoo/member/domain/MemberQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/member/presentation/MemberController.java
backend/src/main/java/com/woowacourse/thankoo/member/presentation/dto/OrganizationMemberResponse.java
backend/src/main/java/com/woowacourse/thankoo/organization/application/OrganizationQueryService.java
backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/organization/presentation/OrganizationController.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/OrganizationAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/MemberAssured.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/OrganizationAssured.java
backend/src/test/java/com/woowacourse/thankoo/common/ControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/member/application/MemberQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/member/presentation/MemberControllerTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/application/OrganizationQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/domain/OrganizationQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/organization/presentation/OrganizationControllerTest.java

refactor: 조직 내 회원 조회 member로 이동한다.

---

backend/src/main/java/com/woowacourse/thankoo/heart/application/HeartService.java
backend/src/main/java/com/woowacourse/thankoo/heart/domain/HeartRepository.java
backend/src/test/java/com/woowacourse/thankoo/heart/application/HeartServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/heart/domain/HeartRepositoryTest.java

refactor: 조직이 다르다면 똑같은 회원에게 마음을 보낼 수 있도록 수정한다.

---

backend/src/main/java/com/woowacourse/thankoo/organization/domain/OrganizationQueryRepository.java

fix: 잘못된 쿼리 수정

---

backend/src/main/java/com/woowacourse/thankoo/admin/qrcode/presentation/dto/AdminLinkResponse.java
backend/src/main/java/com/woowacourse/thankoo/admin/qrcode/presentation/dto/AdminSerialRequest.java
backend/src/main/java/com/woowacourse/thankoo/admin/serial/application/dto/AdminCouponSerialRequest.java
backend/src/main/java/com/woowacourse/thankoo/alarm/application/AlarmEventListener.java
backend/src/main/java/com/woowacourse/thankoo/common/dto/AlarmEvent.java
backend/src/main/java/com/woowacourse/thankoo/common/dto/TimeResponse.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponCommand.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponSelectCommand.java
backend/src/main/java/com/woowacourse/thankoo/coupon/application/dto/CouponUseCommand.java
backend/src/main/java/com/woowacourse/thankoo/heart/presentation/dto/HeartRequest.java
backend/src/main/java/com/woowacourse/thankoo/heart/presentation/dto/HeartResponses.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/dto/MeetingMessage.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/dto/MeetingQueryCondition.java
backend/src/main/java/com/woowacourse/thankoo/organization/presentation/dto/OrganizationResponse.java
backend/src/main/java/com/woowacourse/thankoo/serial/application/dto/CouponSerialRequest.java
backend/src/main/java/com/woowacourse/thankoo/serial/application/dto/SerialCodeRequest.java

- toString 을 재정의 하지 않은 dto에 toString 재정의
- ControllerAdvice에 잘못 매핑한 패키지 이름 수정
Close #580

fix: dto에 toString 재정의

---

backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/coupon/domain/MemberCoupon.java
backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponResponse.java
backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java

refactor: 쿠폰 조회 API 응답 Body에 modifiedAt을 추가한다.

---

frontend/src/components/Main/CouponDetail.tsx

- 모달 애니메이션 pop up event를 부드럽게 변경한다.
변경 전
pop up modal중 애니메이션이 없는 coupon detail 모달창에 대한 애니메이션을 추가하였습니다.
Close #589

refactor: 모달 애니메이션을 부드럽게 변경한다

---

backend/src/main/java/com/woowacourse/thankoo/common/config/DataSourceConfig.java
backend/src/main/java/com/woowacourse/thankoo/common/config/ReplicationDataSourceConfig.java
backend/src/main/java/com/woowacourse/thankoo/common/datasource/DataSourceType.java
backend/src/main/java/com/woowacourse/thankoo/common/datasource/ReplicationRoutingDataSource.java

feat: db replication을 구현한다.

---

frontend/src/components/@shared/Modal/ModalWrapper.tsx
frontend/src/components/Profile/SignOutButton.tsx
frontend/src/hooks/@queries/organization.ts
frontend/src/pages/EnterCouponContent.tsx
frontend/src/pages/Main.tsx
frontend/src/pages/Organization.tsx
frontend/src/pages/SelectReceiver.tsx
frontend/src/routes/AccessController.tsx

- 조직 참여 버튼을 누를 경우 main으로 navigate 후 페이지를 reload해서 organizationId가 제대로 변경 되도록 한다.
- url로 접근 시 url을 파싱해서 해당 organization이 lastAccessed가 되도록 한 후 리다이렉트 해야한다.
- 잘못된 url 입력 시 그냥 main으로 리다이렉트 되도록 한다.
- ModalWrapper에 isDisabled를 넣어 모든 조건에 onClick이 되지는 않도록 한다.
Close #585

fix: QA 중 나온 오류를 수정한다.

---

frontend/src/constants/routes.ts
frontend/src/pages/NotFound.tsx
frontend/src/routes/Router.tsx

- 404 페이지를 추가한다
- 404 페이지는 로그인이 돼 있고 잘못된 url 일때만 보여준다
- 로그인이 안 돼 있을 시 잘못된 url은 로그인 페이지를 보여준다.

feat: 404 page를 추가한다

---

backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/AdminControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/AdminErrorType.java
backend/src/main/java/com/woowacourse/thankoo/admin/organization/exception/AdminInvalidOrganizationException.java
backend/src/main/java/com/woowacourse/thankoo/common/config/DataSourceConfig.java
backend/src/main/java/com/woowacourse/thankoo/common/config/ReplicationDataSourceConfig.java
backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java
backend/src/main/java/com/woowacourse/thankoo/meeting/application/dto/MeetingMessage.java
backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationSentEvent.java

- CouponSentEvent 생성자 순서 변경
- ControllerAdvice defaultPackages 삭제
- Replication DB Profile 수정
Close #594

fix: QA 관련 기능을 수정한다.

---

frontend/src/constants/routes.ts
frontend/src/pages/Hearts.tsx
frontend/src/pages/OrganizationsAccess.tsx
frontend/src/routes/AccessController.tsx
frontend/src/routes/Router.tsx

- organizations를 담당하는 route를 새로 만들어서 담당한다.
Close #598

fix: organizationid로 직접 접근하는 경우에 발생하던 오류를 수정한다. 

---

frontend/src/hooks/@queries/meeting.ts
frontend/src/hooks/CreateReservation/useCreateReservation.ts

- 날짜 계산오류로 인한 오류를 수정
- format이 yymmdd 가 아닌 yyyy로 들어오고 있던 오류 수정

fix: 잘못된 날짜 포매팅으로 인한 오류 수정

---

backend/src/main/java/com/woowacourse/thankoo/common/config/DataSourceConfig.java
backend/src/main/java/com/woowacourse/thankoo/common/config/ReplicationDataSourceConfig.java

- product 환경에서 replication이 적용되도록 수정합니다.
Close #605

feat: prod 환경을 추가한다.

---

frontend/src/components/Hearts/Members.tsx
frontend/src/hooks/CreateReservation/useCreateReservation.ts
frontend/src/hooks/Hearts/useHeartsMembers.tsx
frontend/src/hooks/SelectReceiver/useListViewUsers.ts
frontend/src/pages/CreateReservation.tsx

- 예약 생성 페이지 리다이렉트 오류 수정
- 예약 생성 페이지 날짜 선택 안해도 disable되는 오류 수정
- 하트페이지 유저리스트 스타일 수정
- 유저리스트 사전순 정렬 하도록 수정
- 리스트 조회 안하는 오류 수정
- 하트페이지 유저리스트 count 순 정렬 오류 수정

fix: 최종 QA 수정사항 반영

---

frontend/src/components/Hearts/Members.tsx

- Heart page scroll 디자인 변경
- 다른 페이지와 일관성 있게 변경하였습니다.

fix: Heart page scroll 디자인 변경

---

backend/src/main/java/com/woowacourse/thankoo/admin/serial/domain/AdminCouponSerialQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/serial/application/CouponSerialQueryService.java
backend/src/main/java/com/woowacourse/thankoo/serial/application/CouponSerialService.java
backend/src/main/java/com/woowacourse/thankoo/serial/application/dto/CouponSerialRequest.java
backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerialMember.java
backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerialQueryRepository.java
backend/src/main/java/com/woowacourse/thankoo/serial/presentation/CouponSerialController.java
backend/src/main/java/com/woowacourse/thankoo/serial/presentation/dto/CouponSerialResponse.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponSerialAcceptanceTest.java
backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponSerialAssured.java
backend/src/test/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/admin/serial/domain/AdminCouponSerialQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/serial/application/CouponSerialQueryServiceTest.java
backend/src/test/java/com/woowacourse/thankoo/serial/domain/CouponSerialQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/thankoo/serial/presentation/CouponSerialControllerTest.java

refactor: coupon serial의 api를 변경한다.

---

frontend/src/apis/axios.ts
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/QRCouponRegisterModal.tsx
frontend/src/errors/CustomErrorBoundary.tsx
frontend/src/errors/ErrorFallBack.tsx
frontend/src/hooks/useQRCoupon.tsx

- QR code 에러바운더리 처리를 변경한다.
- QR code 등록에 대한 API 변경점을 반영한다.
- ErrorBoundary의 z index가 낮아서 올바르게 렌더링 되지 않는 오류 수정

fix: QR code 로 쿠폰 API 변경점을 반영한다.

---

frontend/src/apis/axios.ts
frontend/src/components/@shared/Modal.tsx
frontend/src/components/Main/CouponDetail.tsx
frontend/src/components/Main/QRCouponRegisterModal.tsx
frontend/src/components/Organization/OrganizationsDropdown.tsx
frontend/src/errors/CustomError.ts
frontend/src/errors/CustomErrorBoundary.tsx
frontend/src/errors/ErrorFallBack.tsx
frontend/src/hooks/useQRCoupon.tsx

- 페이지 이동 시 모달이 꺼지도록 한다.
- 그룹 추가 버튼 클릭 영역을 넓힌다.

fix: 페이지 이동 시 모달이 꺼지도록 수정한다.
