backend/src/docs/asciidoc/coupon.adoc, backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java, backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepository.java, backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/support/fixtures/CouponRequestFixture.java, backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java
- 보낸 쿠폰 조회 기능을 구현했습니다.
- `/api/coupons/sent`
- 받은 쿠폰의 경우 `사용됨`, `사용전` 과 같은 상태에 따라 조회된다.
- 현재 보낸 쿠폰은 모든 쿠폰을 조회하도록 구현했는데, 보낸 쿠폰 또한 상태에 따라 조회되어야 할까요?
Close #66
=> feat: 보낸 쿠폰 조회 기능을 구현한다.

frontend/src/components/@shared/BottomNavBar.tsx, frontend/src/components/@shared/MyPageButton.tsx, frontend/src/components/@shared/ScheduledPageButton.tsx, frontend/src/components/@shared/SendButton.tsx, frontend/src/constants/api.ts, frontend/src/pages/Main.tsx
- 프로필, 받은 요청, 쿠폰보내기로 이동 가능한 네비게이터 구현
navigator에 버튼이 늘어날 것을 생각하여 버튼을 list안에 넣으면 바로 사용 추가 가능하도록 분리하였음
Close #103
=> feat: 하단 navigator로 페이지 연결(프로필, 받은 요청, 쿠폰보내기)

frontend/src/components/Main/CouponDetails.tsx, frontend/src/components/Main/GridViewCoupon.tsx, frontend/src/constants/coupon.ts, frontend/src/hooks/EnterCouponContent/useEnterCouponContent.ts, frontend/src/hooks/Main/useMain.ts, frontend/src/mocks/dummyData.ts, frontend/src/pages/Reservations.tsx, frontend/src/pages/UserProfile.tsx, frontend/src/types/index.ts
- 사용안된 쿠폰들 간 우선순위를 부여한다.
```jsx
'not-used': 0,
reserving: 1,
reserved: 2,
```
우선순위는 다음과 같다.
Close #128
=> feat: 사용안된 쿠폰들 간 우선순위를 부여한다.

backend/src/docs/asciidoc/coupon.adoc, backend/src/main/java/com/woowacourse/thankoo/common/dto/TimeResponse.java, backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java, backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponQueryService.java, backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java, backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepository.java, backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponStatus.java, backend/src/main/java/com/woowacourse/thankoo/coupon/domain/MemberCoupon.java, backend/src/main/java/com/woowacourse/thankoo/coupon/infrastructure/TimeClient.java, backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java, backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/dto/CouponDetailResponse.java, backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingRepository.java, backend/src/main/java/com/woowacourse/thankoo/member/domain/Member.java, backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationRepository.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/support/fixtures/CouponRequestFixture.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/support/fixtures/ReservationRequestFixture.java, backend/src/test/java/com/woowacourse/thankoo/common/ControllerTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponQueryServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponStatusTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/infrastructure/TimeClientTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/MemberTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationRepositoryTest.java
- 쿠폰 상태에 따라 응답하는 값이 다릅니다.
```java
public TimeResponse getTimeResponse(final Long couponId, final CouponStatus couponStatus) {
validateCouponStatus(couponStatus);
if (couponStatus.isReserving()) {
return TimeResponse.of(getReservation(couponId).getMeetingTime());
}
return TimeResponse.of(getMeeting(couponId).getMeetingTime());
}
``` 
- TimeClient를 분리한 이유는 의존관계를 Meeting -> Coupon, Reservation -> Coupon 처럼 단방향으로 유지하도록 하기 위함입니다.
- 따라서 테스트에서도 고민이 있었는데요.. 현재 프로덕션 코드에서는 모든 의존성을 끊었으나, 테스트에서는 reservationService를참고하고 있습니다. 의존성을 끊기 위해 TimeClient를 Mocking하는 형태도 고민했었는데요. 이 부분에 대한 여러분의 생각은 어떠신가요?
Close #160
=> feat: 단일 쿠폰 조회 기능

backend/src/docs/asciidoc/reservation.adoc, backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java, backend/src/main/java/com/woowacourse/thankoo/common/exception/ForbiddenException.java, backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java, backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java, backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meeting.java, backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java, backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java, backend/src/main/java/com/woowacourse/thankoo/reservation/domain/ReservationStatus.java, backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/ReservationController.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/ReservationAcceptanceTest.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/support/fixtures/ReservationRequestFixture.java, backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingQueryRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/presentation/ReservationControllerTest.java
- 예약 취소 기능 구현
403 에러인 Forbidden은 권한이 없음을 나타냅니다. 예약 삭제 요청할 수 없는 멤버 (예약 신청자가 아닌 경우)가 예약 삭제 요청을 하면 권한 없음 에러를 발생하기 위해 Forbidden 예외를 추가했습니다.
이에 대한 의견 주시면 감사하겠습니다.
검증하는 방식은 아래와 같습니다.
```java
// cancel 도메인 로직
public void cancel(final Member member) {
if (!member.isSameId(memberId)) {
throw new ForbiddenException(ErrorType.FORBIDDEN); 
}
if (!reservationStatus.isWaiting()) {
throw new InvalidReservationException(ErrorType.CAN_NOT_CHANGE_RESERVATION_STATUS);
}
coupon.rollBack();
reservationStatus = ReservationStatus.CANCELED;
}
```
도메인의 행동에 집중하기 위해 coupon은 원래 상태로 돌아간다는 의미인 `rollback`을 사용했습니다. 다른 의견 있으시면 공유 부탁드립니다.
Close #205
=> feat: 예약 취소 기능을 구현한다.

backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java, backend/src/main/java/com/woowacourse/thankoo/common/exception/GlobalControllerAdvice.java, backend/src/main/java/com/woowacourse/thankoo/common/validator/MeetingTimeRequestValidator.java, backend/src/main/java/com/woowacourse/thankoo/common/validator/annotations/ValidMeetingTime.java, backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingTime.java, backend/src/main/java/com/woowacourse/thankoo/reservation/application/dto/ReservationRequest.java, backend/src/main/java/com/woowacourse/thankoo/reservation/presentation/ReservationController.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/ReservationAcceptanceTest.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/ReservationAssured.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingTimeTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/presentation/ReservationControllerTest.java
```java
@Constraint(validatedBy = MeetingTimeRequestValidator.class)
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface ValidMeetingTime {
```
위 애노테이션이 존재하는 클래스를 `MeetingTimeRequestValidator` 클래스로 검증합니다.
- 인수 테스트와 컨트롤러 테스트를 추가했고 도메인 테스트는 제거했습니다.
Close #221
=> refactor: MeetingTime을 웹 요청에서 검증한다.

backend/src/main/java/com/woowacourse/thankoo/coupon/infrastructure/integrate/dto/MeetingResponse.java, backend/src/main/java/com/woowacourse/thankoo/coupon/infrastructure/integrate/dto/ReservationResponse.java, backend/src/main/java/com/woowacourse/thankoo/meeting/domain/ReservationMeetingService.java, backend/src/main/java/com/woowacourse/thankoo/member/domain/Name.java, backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java, backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservedMeetingCreator.java, backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java, backend/src/test/java/com/woowacourse/thankoo/common/fake/FakeReservedMeetingCreator.java, backend/src/test/java/com/woowacourse/thankoo/common/fixtures/ReservationFixture.java, backend/src/test/java/com/woowacourse/thankoo/coupon/infrastructure/integrate/JpaMeetingProviderTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/infrastructure/integrate/JpaReservationProviderTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingQueryRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/ReservationMeetingQueryServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/ReservationMeetingServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/MemberTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/NameTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationQueryRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/domain/ReservationTest.java
- Reservation 생성
이제부터 Reservation을 최초로 생성할 때는 `Reservation.reserve(~~)` 를 사용해주세요.
```java
public static Reservation reserve(final LocalDateTime meetingTime,
final TimeZoneType timeZone,
final ReservationStatus reservationStatus,
final Long memberId,
final Coupon coupon) {
Reservation reservation = new Reservation(meetingTime, timeZone, reservationStatus, memberId, coupon);
reservation.reserve();
return reservation;
}
private void reserve() {
coupon.reserve();
}
```
- ReservationMeetingCreator가 더이상 Reservation 객체를 알지 않아도 되도록 수정했습니다. 더이상 예약과 미팅의 관계는 존재하지 않습니다. 따라서 이름에 대한 변경도 필요해보이긴 하네요. 추천해주세용 (안 변경해도 되구 ㅎ)
Close #258
=> refactor: 예약과 관련한 리팩터링을 진행한다.

backend/src/main/java/com/woowacourse/thankoo/alarm/exception/InvalidAlarmException.java, backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/InMemorySlackUserRepository.java, backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java, backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackClient.java, backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackUserMapper.java, backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/dto/SlackUserResponse.java, backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java, backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java, backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java, backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java, backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupons.java, backend/src/main/java/com/woowacourse/thankoo/meeting/application/MeetingService.java, backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meetings.java, backend/src/main/java/com/woowacourse/thankoo/member/domain/Members.java, backend/src/test/java/com/woowacourse/thankoo/alarm/infrastructure/InMemorySlackUserRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/alarm/infrastructure/SlackUserFixture.java, backend/src/test/java/com/woowacourse/thankoo/common/annotations/ApplicationTest.java, backend/src/test/java/com/woowacourse/thankoo/common/support/AlarmThreadClearExtension.java, backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponsTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingsTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/MembersTest.java, backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
- Member, Coupon, Meeting 관련 일급컬렉션을 생성하여 각 필드를 조회하는 기능을 추가했습니다.
- 스케쥴에서 비즈니스로직을 수행하고 있었는데 이 로직들을 어플리케이션 레이어로 이동시켰습니다.
- 슬랙 userId를 캐싱해두는 InMemorySlackUserRepository에 대한 테스트 케이스를 추가했습니다.
-  null이 반환되지 못 하도록 수정했는데 이 부분 다른 로직으로 해결할 수 있는지 봐주시면 감사해요.
- 알람이 전송됐는지 threadLocal에서 꺼내는 방식으로 테스트를 진행했어요.
사용자의 이메일이 슬랙으로 조회할 수 없는 경우 예외가 발생합니다.
저는 이 부분은 슬랙알림이나 바로 보기 쉬운 로그로 남겨놔야 직접 이메일을 수정해주거나 크루들에게 빠른 피드백이 가능하다고 생각하여
RuntimeException으로 두고 자연스럽게 500에러로 보내게 하여 슬랙 알림이 가도록 생각했는데요.
생각해보니 해당 예외는 이미 백엔드에서 인지하고 있으므로 400대 에러라고 판단이 되었고 이에 관련하여 로그를 어떻게 남길지 같이 고민해보면 좋을 것 가탕요.
Close #268
=> refactor: 알람 관련 기능을 리팩터링한다.

frontend/src/components/CreateReservation/ConfirmReservationModal.tsx, frontend/src/components/EnterCouponContent/ConfirmCouponContentModal.tsx, frontend/src/constants/modal.ts, frontend/src/hooks/useModal.ts
- Mount Animation
- UnMount Animation
최대한 재사용 가능하게 useModal을 변경하였습니다.
사용하고자 하는 Modal Content Component의 최상단 div (대부분의경우 S.container)에 ref={modalContentRef} 를 달아주고
S.Container 안에서 animation 정의만 해주면 됩니다.
ex)
```javascript 
const ConfirmCouponContentModal = () => {
return <S.Container show={visible} ref={modalContentRef}> ...... </S.Container>
}
const S = {
Container: styled.div`
//onMount animation
@keyframes myonmount {
0% {
bottom: -100%;
}
40% {
bottom: -60%;
}
100% {
bottom: 0;
}
}
&.onMount {
animation: myonmount ${`${modalMountTime}ms`} ease-in-out;
}
//unMount animation
@keyframes myunmount {
0% {
bottom: 0%;
}
100% {
bottom: -100%;
}
}
&.unMount {
animation: myunmount ${`${modalUnMountTime}ms`} ease-in-out;
}
`,
```
- useModal의 close에서 최대한 추상화 하다보니까 document.getElementByClassName을 …
=> feat: 모달창 마운트, 언마운트시 애니메이션 장착

frontend/src/components/@shared/HeaderText.tsx, frontend/src/components/@shared/noContent/NoReceivedCoupon.tsx, frontend/src/components/@shared/noContent/NoReservation copy.tsx, frontend/src/components/@shared/noContent/NoSendCoupon.tsx, frontend/src/hooks/Main/domain/useMain.ts, frontend/src/hooks/Main/queries/coupons.ts, frontend/src/pages/Main.tsx
- 받은 쿠폰함, 보낸 쿠폰함 nav를 한번에 보여주고 클릭 시 slide animation을 한다
- 빈 페이지 새 그림에 기본 height를 줘서 reflow(icon 공간 없어서 작아져 있다가 늘어 나는 거)를 방지했다.
Close #302
=> feat: 메인 페이지 받은, 보낸 쿠폰함 한번에 보이기

backend/src/main/java/com/woowacourse/thankoo/member/presentation/MemberController.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/MemberAcceptanceTest.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/MemberAssured.java, backend/src/test/java/com/woowacourse/thankoo/member/presentation/MemberControllerTest.java
- 회원 이름 api url을 /api/members/me 에서 /api/members/me/name 으로 수정했습니다.
Close #295
=> refactor: 회원 이름 변경 api url 수정

backend/src/docs/asciidoc/coupon.adoc, backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponStatusGroup.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java, backend/src/test/java/com/woowacourse/thankoo/common/fixtures/CouponFixture.java, backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponQueryServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponQueryRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponStatusGroupTest.java, backend/src/test/java/com/woowacourse/thankoo/coupon/presentation/CouponControllerTest.java, backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingQueryRepositoryTest.java
- GET /api/coupons/received?status=all
- CouponStatusGroup 에 ALL 그룹을 추가했습니다.
- 테스트 코드에서 쿠폰을 여러 개 저장할 때 save() 를 여러번 호출하는 경우 saveAll()로 저장하도록 변경했습니다.
- 트랜잭션을 여러번 생성하지 않아도 되기 때문에 이 방법을 선택했습니다.
```
couponRepository.save(new Coupon(sender.getId(), receiver.getId(),
new CouponContent(TYPE, TITLE, MESSAGE), CouponStatus.NOT_USED));
couponRepository.save(new Coupon(sender.getId(), receiver.getId(),
new CouponContent(TYPE, TITLE, MESSAGE), CouponStatus.RESERVED));
couponRepository.save(new Coupon(sender.getId(), receiver.getId(),
new CouponContent(TYPE, TITLE, MESSAGE), CouponStatus.USED));
```
```
couponRepository.saveAll(List.of(
new Coupon(sender.getId(), receiver.getId(), new CouponContent(TYPE, TITLE, MESSAGE),
CouponStatus.NOT_USED),
new Coupon(sender.getId(), receiver.getId(), new …
```
=> feat: 모든 받은 쿠폰 조회 기능

backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java, backend/src/main/java/com/woowacourse/thankoo/common/schedule/ReservationScheduleTask.java, backend/src/main/java/com/woowacourse/thankoo/meeting/application/MeetingService.java, backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java
```java
@Scheduled(cron = "0 0/30 10-19 * * *")
void executeCancelExpiredReservation() {
log.debug("[Scheduling] 만료된 예약 취소 처리");
reservationService.cancelExpiredReservation(LocalDateTime.now());
}
```
- DB 에 `2022-08-05 19:30:00` 와 같이 초 단위가 0으로 저장됨
- `LocalDateTime.now()` 시점의 Time이 0초가 아닐 수 있기 때문에 해당하는 만남/예약 조회시 예상과 다르게 조회되지 않음
-  분 단위까지만 현재 시간을 적용하고 초 단위는 0초로 설정하여 처리하도록 수정
```java
@Scheduled(cron = "0 0/30 10-19 * * *")
void executeCancelExpiredReservation() {
log.debug("[Scheduling] 만료된 예약 취소 처리");
LocalDateTime nowDateTime = LocalDateTime.now();
LocalTime nowTime = LocalTime.of(nowDateTime.getHour(), nowDateTime.getMinute());
LocalDateTime reservationTime = LocalDateTime.of(nowDateTime.toLocalDate(), nowTime);
reservationService.cancelExpiredReservation(reservationTime);
}
```
Close …
=> refactor: 만남 완료 / 만료된 예약 스케줄링시 시간 설정 방식 변경 

backend/src/docs/asciidoc/index.adoc, backend/src/docs/asciidoc/serial.adoc, backend/src/main/java/com/woowacourse/thankoo/admin/qrcode/application/AdminQrCodeService.java, backend/src/main/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialQueryService.java, backend/src/main/java/com/woowacourse/thankoo/member/domain/MemberQueryRepository.java, backend/src/main/java/com/woowacourse/thankoo/serial/application/CouponSerialQueryService.java, backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerial.java, backend/src/main/java/com/woowacourse/thankoo/serial/domain/SerialCode.java, backend/src/main/java/com/woowacourse/thankoo/serial/presentation/CouponSerialController.java, backend/src/main/java/com/woowacourse/thankoo/serial/presentation/dto/CouponSerialResponse.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponSerialAcceptanceTest.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponAssured.java, backend/src/test/java/com/woowacourse/thankoo/acceptance/builder/CouponSerialAssured.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/MemberQueryRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/serial/application/CouponSerialQueryServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/serial/presentation/CouponSerialControllerTest.java
- code 로 쿠폰 시리얼을 조회합니다.
엔티티에 unique 조건과 길이를 조절했어요.
특이사항으로는 쿠폰을 조회할 때 memberId를 받아오는데 존재하는 회원인지 확인하기 위해 jpa의 `existsById()`를 사용했는데 `limit` 조건이 안붙더라구요. 그래서 아예 Jdbc를 사용해서 `exists` 쿼리를 사용하도록 수정했어요.
Close #433
=> feat: 시리얼 번호로 쿠폰 시리얼을 조회한다.

frontend/src/components/Main/QRCouponRegisterModal.tsx
- QR 쿠폰을 등록하는 모달에서 등록 or 거절을 클릭 시 로컬 스토리지에서 query를 삭제한다.
- 그러나 아직 esc나 deemed를 클릭했을 때 로컬 스토리지를 비우고 메인 페이지로 리다이렉트하는 로직은 구현하지 못했다.
Close #471
=> fix: 승낙, 거절 후 로컬 스토리지 query 삭제

frontend/src/components/Main/QRCouponRegisterModal.tsx, frontend/src/hooks/useQRCoupon.tsx
- navigate에 replace:true 옵션을 넣어서 navigate 시 히스토리가 쌓이지 않도록 한다.
Close #475
=> fix: qr 코드 등록, 취소 후 리다이렉트가 기록이 남지 않도록 한다.

frontend/src/components/@shared/Layout/PageLayout.tsx, frontend/src/components/Main/GridViewCoupons.tsx, frontend/src/pages/Main.tsx
- GridViewCoupons에 padding-bottom을 줘서 짤리는 부분이 없도록 했다.
- 공통 Layout의 width가 커진 것 같아서 조금 줄였습니다.
**AS-IS**
**TO-BE**
Close #506
=> fix: main 페이지 하단에 짤리는 부분이 없도록 한다.

frontend/src/components/@shared/ConditionalViewer.tsx, frontend/src/components/Reservations/ListViewReservation.tsx, frontend/src/hooks/@queries/meeting.ts, frontend/src/hooks/CreateReservation/useCreateReservation.ts, frontend/src/hooks/Main/useCouponDetail.ts, frontend/src/hooks/Main/useMain.ts, frontend/src/hooks/Meetings/useMeetings.ts, frontend/src/pages/CreateReservation.tsx, frontend/src/pages/Meetings.tsx, frontend/src/types/coupon.ts, frontend/src/types/meeting.ts, frontend/src/utils/date.ts
- 쿠폰 즉시 사용 기능을 연동한다.
- 홈 화면에서 유저가 `볼 수 있는 쿠폰 상태`와 `볼 수 없는 쿠폰 상태`를 각각 타입으로 만들고 구분한다.
Close #526
=> feat: 쿠폰 즉시 사용 api 연동

frontend/src/components/@shared/Button.tsx, frontend/src/components/@shared/LongButton.tsx, frontend/src/components/@shared/noContent/NoReceivedCoupon.tsx, frontend/src/components/@shared/noContent/NoSendCoupon.tsx, frontend/src/components/CreateReservation/ConfirmReservationModal.tsx, frontend/src/components/CreateReservation/CreateReservationSuccess.tsx, frontend/src/components/EnterCouponContent/ConfirmCouponContentModal.tsx, frontend/src/components/EnterCouponContent/EnterCouponContentSuccess.tsx, frontend/src/components/Main/CouponDetail.reservation.tsx, frontend/src/components/Main/CouponDetail.tsx, frontend/src/components/Main/QRCouponRegisterModal.tsx, frontend/src/components/Profile/SelectProfileImgModal.tsx, frontend/src/hooks/Main/useCouponDetail.ts, frontend/src/pages/CreateReservation.tsx, frontend/src/pages/EnterCouponContent.tsx, frontend/src/pages/EnterNickname.tsx, frontend/src/pages/Organization.tsx, frontend/src/pages/SelectReceiver.tsx, frontend/src/types/coupon.ts
- 커스텀 Button 컴포넌트를 생성하고 해당 컴포넌트로 다 통일한다.
- props로는 size와 color, isDisabled를 받는다.
- size로 height를 조절하며 width는 100%로 고정이다. width를 줄이고 싶다면 사용하는 곳에서 wrapper를 만드는 식으로 사용한다. size 기반으로 font-size도 고정이다.
- color는 primary,primaryLight,secondary,secondaryLight가 있다. 해당 색에 맞게 폰트 색도 변경된다. 따로 지정할 수는 없게했다.
- isDisabled를 통해 click event를 막고 disabled 스타일을 적용하도록 했다. button의 disabled 옵션을 사용할까 했지만, 실제 html 옵션을 사용하면 개발자도구에서 해당 attribute를 제거하는 방법으로 문제가 생길 수 있을 것 같아서 isDisabled라는 이름의 local state 기반으로 판단하도록 했다.
=> refactor: Button 컴포넌트 생성

backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java, backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meeting.java, backend/src/main/java/com/woowacourse/thankoo/member/domain/Email.java, backend/src/main/java/com/woowacourse/thankoo/member/domain/Member.java, backend/src/main/java/com/woowacourse/thankoo/member/domain/Name.java, backend/src/test/java/com/woowacourse/thankoo/common/fixtures/AuthenticationFixture.java, backend/src/test/java/com/woowacourse/thankoo/common/fixtures/MemberFixture.java, backend/src/test/java/com/woowacourse/thankoo/member/application/MemberServiceTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/EmailTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/MemberRepositoryTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/MemberTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/MembersTest.java, backend/src/test/java/com/woowacourse/thankoo/member/domain/NameTest.java, backend/src/test/java/com/woowacourse/thankoo/member/presentation/MemberControllerTest.java
- 어제 새벽에 마무리하려했는데 조금 늦어졌어요.
- 다음 작업은 도커 작업과 시리얼 리팩토링을 진행하겠습니다.
- 수정한 부분에 대해선 코멘트로 설명 남겨둘게요.
- 이번 리팩토링은 구조나 패턴의 변경이 아니라 컨벤션과 변수명 관련해서 수정된 부분이 대부분이에요.
나머지 도메인들에 대한 부분들도 시간내서 조금씩 확인해볼게요. 
Close #511 
```sql
alter table member modify column email not null;
alter table member modify column socail_id not null;
alter table member modify column image_url varchar(2000) not null;
```
다음과 같은 쿼리를 사용할건데 확인 부탁드려요
=> refactor: 회원 관련 테스트 추가 및 리팩토링을 한다.

frontend/src/components/@shared/PageSlider.tsx, frontend/src/components/Main/CouponDetail.reservation.tsx, frontend/src/components/Main/GridViewCoupons.tsx, frontend/src/mocks/dummyData.ts, frontend/src/types/coupon.ts, frontend/src/utils/date.ts
- 즉시사용이 제대로 된 날짜를 보여주도록 변경한다.
- 즉시사용 날짜 
- 예약 후 사용완료 날짜
- 예약 완료 날짜
Close #592
=> feat: 즉시사용인 경우 즉시 사용을 누른 시간을 보여주도록 변경

frontend/src/hooks/@queries/coupon.ts
- 값이 없을 때 api call을 해서 path가 null이었던 문제가 있었다.
- useErrorBoundary를 false로 해서 에러가 전파되는 것을 방지했다.
=> fix: create-reservation 페이지 접근 시 에러가 발생하던 오류를 수정한다.
